const NOT_FOUND_STATUS = 404;
const BAD_REQUEST_STATUS = 400;
const SERVER_ERROR_STATUS = 500;
const CONFLICT_STATUS = 409;
const UNAUTHORIZED = 401;

module.exports = {
  NOT_FOUND_STATUS,
  BAD_REQUEST_STATUS,
  SERVER_ERROR_STATUS,
  CONFLICT_STATUS,
  UNAUTHORIZED,
};
